# Generated by Django 4.0.4 on 2022-05-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0010_profile_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
