# Generated by Django 3.2.7 on 2022-05-21 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0014_remove_srp_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='srp',
            name='image',
            field=models.ImageField(null=True, upload_to='images/lesson'),
        ),
        migrations.CreateModel(
            name='laboratorywork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField()),
                ('document', models.FileField(null=True, upload_to='pdf/document')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universystem.lesson')),
            ],
        ),
    ]
