# Generated by Django 4.0.4 on 2022-05-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0011_lesson_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/lesson')),
                ('document', models.FileField(null=True, upload_to='pdf/document')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universystem.lesson')),
            ],
        ),
    ]
