# Generated by Django 4.1.7 on 2023-04-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universystem', '0016_remove_srp_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='images/lesson')),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
